specfile_path: libpkgmanifest.spec

files_to_sync:
  - libpkgmanifest.spec
  - .packit.yaml

upstream_package_name: libpkgmanifest
downstream_package_name: libpkgmanifest

jobs:
- job: propose_downstream
  trigger: release
  dist_git_branches:
    - fedora-rawhide
  copy_upstream_release_description: false
- job: koji_build
  trigger: commit
  dist_git_branches:
    - fedora-all
- job: bodhi_update
  trigger: commit
  dist_git_branches:
    - fedora-all
- job: copr_build
  trigger: commit
  owner: rpmsoftwaremanagement
  project: libpkgmanifest-nightly
  targets:
    - fedora-all
